clusterName: ""
region: "fsn1"
sshKeyName: ""
hetznerSecretName: "hetzner"

clusterNetwork:
  pods:
    cidrBlock: "10.244.0.0/16"
  services:
    cidrBlock: "10.96.0.0/12"

k0s:
  version: "v1.34.4+k0s.0"

worker:
  serverType: "cpx22"
  imageName: "ubuntu-24.04"
  replicas: 2

ingress:
  enabled: false
  apiHost: ""
  konnectivityHost: ""
  className: "haproxy"
  port: 443
  annotations:
    haproxy.org/ssl-passthrough: "true"
