apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - {{ .Values.clusterNetwork.pods.cidrBlock }}
    services:
      cidrBlocks:
        - {{ .Values.clusterNetwork.services.cidrBlock }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: {{ .Values.clusterName }}-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HetznerCluster
    name: {{ .Values.clusterName }}
