{{/*
HetznerCluster resource - Hetzner Cloud infrastructure configuration
This resource defines the Hetzner Cloud infrastructure including:
- Load balancer for control plane access (forwards to hosted control plane)
- Private networking configuration (optional)
- SSH keys and placement groups for worker nodes
- API token reference for Hetzner Cloud API access
*/}}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: {{ include "cluster.name" . }}
  finalizers:
    - k0rdent.mirantis.com/cleanup
spec:
  controlPlaneRegions:
    - {{ .Values.region }}
  {{- if .Values.sshKeyNames }}
  sshKeys:
    hcloud:
    {{- range .Values.sshKeyNames }}
      - name: {{ . }}
    {{- end }}
  {{- end }}
  hcloudTokenRef:
    name: {{ .Values.tokenRef.name }}
    key: {{ .Values.tokenRef.key }}
  {{- if .Values.placementGroupName }}
  placementGroups:
    - name: {{ .Values.placementGroupName }}
      type: spread
  {{- end }}
  {{- if .Values.labels }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
  controlPlaneLoadBalancer:
    enabled: false  # Disabled for hosted control plane - uses management cluster ingress instead
  controlPlaneEndpoint:
    # Ingress configuration for worker nodes
    # Worker nodes connect to control plane via ingress hostname
    host: {{ .Values.controlPlane.ingress.apiHost | quote }}
    port: 443  # HTTPS port for ingress
  {{- if .Values.hcloudNetwork }}
  hcloudNetwork:
    enabled: {{ .Values.hcloudNetwork.enabled }}
    cidrBlock: {{ .Values.hcloudNetwork.cidrBlock | quote }}
    subnetCidrBlock: {{ .Values.hcloudNetwork.subnetCidrBlock | quote }}
    networkZone: {{ .Values.hcloudNetwork.networkZone | quote }}
  {{- end }}
  hetznerSecretRef:
    name: {{ .Values.tokenRef.name }}
    key:
      hcloudToken: {{ .Values.tokenRef.key }}
