{{/*
HetznerCluster resource - Hetzner Cloud infrastructure configuration
Supports three control plane access modes:
- LoadBalancer (default): Hetzner CCM provisions a dedicated LB for the hosted control plane
- NodePort: Workers connect via management cluster node/LB IP and NodePort
- Ingress: Workers connect via HAProxy ingress hostnames
*/}}
{{- $useIngress := and .Values.controlPlane.ingress .Values.controlPlane.ingress.apiHost }}
{{- $useLB := eq (.Values.controlPlane.service.type | default "LoadBalancer") "LoadBalancer" }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: {{ include "cluster.name" . }}
  finalizers:
    - k0rdent.mirantis.com/cleanup
spec:
  controlPlaneRegions:
    - {{ .Values.region }}
  {{- if .Values.sshKeyNames }}
  sshKeys:
    hcloud:
    {{- range .Values.sshKeyNames }}
      - name: {{ . }}
    {{- end }}
  {{- end }}
  hcloudTokenRef:
    name: {{ .Values.tokenRef.name }}
    key: {{ .Values.tokenRef.key }}
  {{- if .Values.placementGroupName }}
  placementGroups:
    - name: {{ .Values.placementGroupName }}
      type: spread
  {{- end }}
  {{- if .Values.labels }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
  controlPlaneLoadBalancer:
    enabled: false  # Disabled for hosted control plane (handled by k0smotron service)
  controlPlaneEndpoint:
    {{- if $useIngress }}
    host: {{ .Values.controlPlane.ingress.apiHost | quote }}
    port: 443
    {{- else if $useLB }}
    # LoadBalancer mode: endpoint will be populated by Hetzner CCM
    # Temporary placeholder - CAPH requires a non-empty host
    host: {{ .Values.controlPlane.endpoint.host | default "pending" | quote }}
    port: 6443
    {{- else }}
    # NodePort mode
    host: {{ required "controlPlane.endpoint.host is required for NodePort mode" .Values.controlPlane.endpoint.host | quote }}
    port: {{ .Values.controlPlane.service.apiNodePort | default 30443 }}
    {{- end }}
  {{- if .Values.hcloudNetwork }}
  hcloudNetwork:
    enabled: {{ .Values.hcloudNetwork.enabled }}
    cidrBlock: {{ .Values.hcloudNetwork.cidrBlock | quote }}
    subnetCidrBlock: {{ .Values.hcloudNetwork.subnetCidrBlock | quote }}
    networkZone: {{ .Values.hcloudNetwork.networkZone | quote }}
  {{- end }}
  hetznerSecretRef:
    name: {{ .Values.tokenRef.name }}
    key:
      hcloudToken: {{ .Values.tokenRef.key }}
