apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ .Values.clusterName }}-cp
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Values.k0s.version }}
  persistence:
    type: emptyDir
  service:
    type: ClusterIP
    apiPort: 6443
    konnectivityPort: 8132
  {{- if and .Values.ingress.enabled .Values.ingress.apiHost .Values.ingress.konnectivityHost }}
  ingress:
    deploy: true
    apiHost: {{ .Values.ingress.apiHost }}
    konnectivityHost: {{ .Values.ingress.konnectivityHost }}
    className: {{ .Values.ingress.className }}
    port: {{ .Values.ingress.port }}
    {{- if .Values.ingress.annotations }}
    annotations:
      {{- toYaml .Values.ingress.annotations | nindent 6 }}
    {{- end }}
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    spec:
      extensions:
        helm:
          repositories:
            - name: hcloud
              url: https://charts.hetzner.cloud
          charts:
            - name: hcloud-cloud-controller-manager
              chartname: hcloud/hcloud-cloud-controller-manager
              namespace: kube-system
              values: |
                env:
                  HCLOUD_TOKEN:
                    valueFrom:
                      secretKeyRef:
                        name: hetzner
                        key: hcloud
                  KUBERNETES_SERVICE_HOST:
                    value: {{ .Values.ingress.apiHost | quote }}
                  KUBERNETES_SERVICE_PORT:
                    value: {{ .Values.ingress.port | quote }}
                networking:
                  enabled: true
  {{- end }}
