apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: {{ .Values.clusterName }}-machine-config
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      version: {{ .Values.k0s.version }}
      args:
        - --labels=node.kubernetes.io/role=worker
      {{- if .Values.ingress.enabled }}
        - --kubelet-extra-args="--cloud-provider=external"
      {{- end }}
